Transform: 'AWS::Serverless-2016-10-31'
Resources:
    GetShippingPrice:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs4.3
            CodeUri: ./
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /shipping
                  Method: get
